name: Build macOS App

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'model/**'
      - 'icons/**'
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  Build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Viewer dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Run PyInstaller for Viewer
        run: |
          pyinstaller src/trailcam_classifier_app/viewer.py \
            --name TrailcamViewer \
            --windowed

      - name: Install GUI dependencies
        run: |
          pip install .[gui]

      - name: Run PyInstaller for GUI
        run: |
          pyinstaller src/trailcam_classifier_app/gui.py \
            --name TrailcamClassifier \
            --windowed \
            --add-data "model:model" \
            --icon "icons/ClassifierIcon.png"

      - name: Package Viewer application
        run: |
          hdiutil create -volname "TrailcamViewer" -srcfolder "dist/TrailcamViewer.app" -ov -format UDZO "TrailcamViewer.dmg"

      - name: Package GUI application
        run: |
          hdiutil create -volname "TrailcamClassifier" -srcfolder "dist/TrailcamClassifier.app" -ov -format UDZO "TrailcamClassifier.dmg"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Viewer
          path: TrailcamViewer.dmg

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: GUI
          path: TrailcamClassifier.dmg

  CreateRelease:
    needs: [ Build ]
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && github.event.action == 'closed' && github.ref == 'refs/heads/main' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - uses: actions/download-artifact@v4
        with:
          name: GUI
          path: .

      - uses: actions/download-artifact@v4
        with:
          name: Viewer
          path: .

      - name: Generate tag
        id: tag
        run: echo "TAG_NAME=release-$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: ${{ env.TAG_NAME }}
          body: |
            Automated build of the latest version of the Trailcam Classifier GUI.
          make_latest: true
          files: |
            TrailcamClassifier.dmg
            TrailcamViewer.dmg
